#!/bin/bash
echo "Version"
cat VERSION
echo "Working dir"
pwd
echo "Folder content"
ls -la
docker build --build-arg VCS_REF=`git rev-parse — short HEAD` \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg VERSION=`cat VERSION` \
  -t $IMAGE_NAME .
